spring:
    application:
        name: main-application
    profiles:
        include:
          - oauth

    datasource:
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        security: trace
        web: DEBUG
    hibernate:
      orm:
        jdbc:
          bind: trace

server:
  servlet:
    context-path: /yapp

swagger:
  version: ${SWAGGER_VERSION:0.0.1}
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    syntax-highlight:
      theme: none
    urls-primary-name: INSTEAD API DOCS