spring:
    application:
        name: domain-module

    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc.time_zone: Asia/Seoul
