spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc.time_zone: Asia/Seoul

logging:
  level:
    org:
      springframework:
        security: debug
        web: DEBUG
    hibernate:
      orm:
        jdbc:
          bind: trace
