spring:
    application:
        name: main-app
    profiles:
        include:
            - oauth
            - docs
    jackson:
        time-zone: Asia/Seoul

    cloud:
        aws:
            region:
                static: ${AWS_REGION}
            credentials:
                access-key: ${AWS_ACCESS_KEY}
                secret-key: ${AWS_SECRET_KEY}
            s3:
                bucket-name: ${AWS_S3_BUCKET}
                url-prefix: ${AWS_S3_URL_PREFIX}

logging:
    level:
        org:
            springframework:
                security: debug
                web: DEBUG
        hibernate:
            orm:
                jdbc:
                    bind: trace

server:
    servlet:
        context-path: /yapp

# Client - 이후에 open-ai모듈로 로직과 함께 빠져야함
client:
    news-parser:
        url: ${NEWS_PARSER_URL}

    openai:
        url: https://api.openai.com/v1/chat/completions
        key: ${OPENAI_API_KEY}
        model: gpt-4o-mini
