spring:
  config:
    activate:
      on-profile: "aws"

  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: ${AWS_S3_BUCKET}
        url-prefix: ${AWS_S3_URL_PREFIX}
